In [63]:
pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=7596bcc7cca87d3231454e1f3a8f0ac3d252b4f07908d8b331dc1346fd3bdc75
  Stored in directory: /root/.cache/pip/wheels/4b/c3/77/a5f48aeb0d3efb7cd5ad61cbd3da30bbf9ffc9662b07c9f879
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [64]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [21]:
df = pd.read_csv('homeprices2.csv')
df

   area   bedroom  age   price
0   2600      3.0   20  550000
1   3000      4.0   15  565000
2   3200      NaN   18  610000
3   3600      3.0   30  595000
4   4000      5.0    8  760000
5   4100      6.0    8  810000

In [6]:
df.bedroom.median()

4.0

In [5]:
df.bedroom = df.bedroom.fillna(df.bedroom.median())
df

   area   bedroom  age   price
0   2600      3.0   20  550000
1   3000      4.0   15  565000
2   3200      4.0   18  610000
3   3600      3.0   30  595000
4   4000      5.0    8  760000
5   4100      6.0    8  810000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [8]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540396

In [10]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([498408.25158031])

In [11]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [12]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([578876.03748933])

In [58]:
df = pd.read_csv('hiring.csv')
df

   experience  test_score  interview_score  salary_dollar
0           0         8.0                9          50000
1           0         8.0                6          45000
2           5         6.0                7          60000
3           2        10.0               10          65000
4           7         9.0                6          70000
5           3         7.0               10          62000
6          10         NaN                7          72000
7          11         7.0                8          80000

In [45]:
df.experience.mean()

6.333333333333333

In [59]:
df.experience.median()

4.0

In [46]:
df.experience = df.experience.fillna(df.experience.mean())
df

   experience  test_score  interview_score  salary_dollar
0    6.333333         8.0                9          50000
1    6.333333         8.0                6          45000
2    5.000000         6.0                7          60000
3    2.000000        10.0               10          65000
4    7.000000         9.0                6          70000
5    3.000000         7.0               10          62000
6   10.000000         NaN                7          72000
7   11.000000         7.0                8          80000

In [62]:
df.experience = df.experience(df.experience.median())
df

TypeError: ignored

In [47]:
df.test_score.mean()

7.857142857142857

In [54]:
df.test_score.median()

7.928571428571429

In [48]:
df.test_score = df.test_score.fillna(df.test_score.mean())
df

   experience  test_score  interview_score  salary_dollar
0    6.333333    8.000000                9          50000
1    6.333333    8.000000                6          45000
2    5.000000    6.000000                7          60000
3    2.000000   10.000000               10          65000
4    7.000000    9.000000                6          70000
5    3.000000    7.000000               10          62000
6   10.000000    7.857143                7          72000
7   11.000000    7.000000                8          80000

In [57]:
df.test_score = df.test_score.fillna(df.test_score.median())
df

   experience  test_score  interview_score  salary_dollar
0    6.333333    8.000000                9          50000
1    6.333333    8.000000                6          45000
2    5.000000    6.000000                7          60000
3    2.000000   10.000000               10          65000
4    7.000000    9.000000                6          70000
5    3.000000    7.000000               10          62000
6   10.000000    7.857143                7          72000
7   11.000000    7.000000                8          80000

In [50]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary_dollar',axis='columns'),df.salary_dollar)

LinearRegression()

In [51]:
reg.predict([[2,6,9]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([52490.47384674])

In [52]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([86424.66795913])